USE PokemonVGC;

DROP TABLE IF EXISTS HeldItem;

CREATE TABLE HeldItem
(
itemID INT NOT NULL IDENTITY
	CONSTRAINT PK_HeldItem PRIMARY KEY,
itemName NVARCHAR (30),
itemEffect NVARCHAR (200)
);

SELECT * FROM HeldItem;

INSERT INTO HeldItem (itemName, itemEffect)
VALUES
(' Aguav Berry','Restores HP if it is low, but may cause confusion.'),
(' Apicot Berry','Raises Special Defense when HP is low.'),
(' Aspear Berry','If held by a Pokémon, it defrosts it.'),
(' Babiri Berry','Weakens a supereffective Steel-type attack against the holding Pokémon.'),
(' Belue Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(' Bluk Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(' Charti Berry','Weakens a supereffective Rock-type attack against the holding Pokémon.'),
(' Cheri Berry','If held by a Pokémon, it recovers from paralysis.'),
(' Chesto Berry','If held by a Pokémon, it recovers from sleep.'),
(' Chilan Berry','Weakens a Normal-type attack against the Pokémon holding this berry.'),
(' Chople Berry','Weakens a supereffective Fighting-type attack against the holding Pokémon.'),
(' Coba Berry','Weakens a supereffective Flying-type attack against the holding Pokémon.'),
(' Colbur Berry','Weakens a supereffective Dark-type attack against the holding Pokémon.'),
(' Cornn Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(' Custap Berry','Holder can move first when HP is low.'),
(' Durin Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(' Enigma Berry','If held by a Pokémon, it restores its HP if it is hit by any supereffective attack.'),
(' Figy Berry','Restores HP if it is low, but may cause confusion.'),
(' Ganlon Berry','Raises Defense when HP is low.'),
(' Golden Nanab Berry','Drastically calms a Pokémon in battle, in Lets Go Pikachu/Eevee.'),
(' Golden Pinap Berry','Drastically increases chance of getting items when a Pokémon is caught, in Pokémon Lets Go.'),
(' Golden Razz Berry','Makes a Pokémon easier to catch in Pokémon Lets Go.'),
(' Grepa Berry','Increases Friendship but lowers Special Defense EVs.'),
(' Haban Berry','Weakens a supereffective Dragon-type attack against the holding Pokémon.'),
(' Hondew Berry','Increases Friendship but lowers Special Attack EVs.'),
(' Iapapa Berry','Restores HP if it is low, but may cause confusion.'),
(' Jaboca Berry','If held by a Pokémon and a physical attack lands, the attacker also takes damage.'),
(' Kasib Berry','Weakens a supereffective Ghost-type attack against the holding Pokémon.'),
(' Kebia Berry','Weakens a supereffective Poison-type attack against the holding Pokémon.'),
(' Kee Berry','If held by a Pokémon, this Berry will increase the holders Defense if it is hit with a physical move.'),
(' Kelpsy Berry','Increases Friendship but lowers Attack EVs.'),
(' Lansat Berry','Increases critical-hit ratio when HP is low.'),
(' Leppa Berry','If held by a Pokémon, it restores a moves PP by 10.'),
(' Liechi Berry','Raises Attack when HP is low.'),
(' Lum Berry','If held by a Pokémon, it recovers from any status problem.'),
(' Mago Berry','Restores HP if it is low, but may cause confusion.'),
(' Magost Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(' Maranga Berry','If held by a Pokémon, this Berry will increase the holders Sp. Def if it is hit with a special move.'),
(' Micle Berry','Increases a moves accuracy when HP is low.'),
(' Nanab Berry','A Berry to be used in cooking. Calms a Pokémon in battle, in Lets Go Pikachu/Eevee.'),
(' Nomel Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(' Occa Berry','Weakens a supereffective Fire-type attack against the holding Pokémon.'),
(' Oran Berry','If held by a Pokémon, it heals the user by just 10 HP.'),
(' Pamtre Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(' Passho Berry','Weakens a supereffective Water-type attack against the holding Pokémon.'),
(' Payapa Berry','Weakens a supereffective Psychic-type attack against the holding Pokémon.'),
(' Pecha Berry','If held by a Pokémon, it recovers from poison.'),
(' Persim Berry','If held by a Pokémon, it recovers from confusion.'),
(' Petaya Berry','Raises Special Attack when HP is low.'),
(' Pinap Berry','A Berry to be used in cooking. Increases chances of getting items when a Pokémon is caught, in Pokémon Lets Go.'),
(' Pomeg Berry','Increases Friendship but lowers HP EVs.'),
(' Qualot Berry','Increases Friendship but lowers Defense EVs.'),
(' Rabuta Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(' Rawst Berry','If held by a Pokémon, it recovers from a burn.'),
(' Razz Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(' Rindo Berry','Weakens a supereffective Grass-type attack against the holding Pokémon.'),
(' Roseli Berry','If held by a Pokémon, this Berry will lessen the damage taken from one supereffective Fairy-type attack.'),
(' Rowap Berry','If held by a Pokémon and a special attack lands, the attacker also takes damage.'),
(' Salac Berry','Raises Speed when HP is low.'),
(' Shuca Berry','Weakens a supereffective Ground-type attack against the holding Pokémon.'),
(' Silver Nanab Berry','Greatly calms a Pokémon in battle, in Lets Go Pikachu/Eevee.'),
(' Silver Pinap Berry','Greatly increases chance of getting items when a Pokémon is caught, in Pokémon Lets Go.'),
(' Silver Razz Berry','Makes a Pokémon easier to catch in Pokémon Lets Go.'),
(' Sitrus Berry','If held by a Pokémon, it heals the users HP a little.'),
(' Spelon Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(' Starf Berry','Sharply raises a random stat when HP is low.'),
(' Tamato Berry','Increases Friendship but lowers Speed EVs.'),
(' Tanga Berry','Weakens a supereffective Bug-type attack against the holding Pokémon.'),
(' Wacan Berry','Weakens a supereffective Electric-type attack against the holding Pokémon.'),
(' Watmel Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(' Wepear Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(' Wiki Berry','Restores HP if it is low, but may cause confusion.'),
(' Yache Berry','Weakens a supereffective Ice-type attack against the holding Pokémon.'),
(' Ability Capsule','A capsule that allows a Pokémon with two Abilities to switch between these Abilities when it is used.'),
(' Abomasite','Enables Abomasnow to Mega Evolve during battle.'),
(' Absolite','Enables Absol to Mega Evolve during battle.'),
(' Absorb Bulb','A consumable bulb. If the holder is hit by a Water-type move, its Sp. Atk will rise.'),
(' Adamant Orb','Increases the power of Dragon- and Steel-type moves when held by Dialga.'),
(' Adrenaline Orb','Using it makes wild Pokémon more likely to call for help. If held by a Pokémon, it boosts Speed when intimidated. It can be used only once.'),
(' Aerodactylite','Enables Aerodactyl to Mega Evolve during battle.'),
(' Aggronite','Enables Aggron to Mega Evolve during battle.'),
(' Air Balloon','When held by a Pokémon, the Pokémon will float into the air. When the holder is attacked, this item will burst.'),
(' Alakazite','Enables Alakazam to Mega Evolve during battle.'),
(' Aloraichium Z','Allows Alolan Raichu to upgrade Thunderbolt to a Z-Move, Stoked Sparksurfer.'),
(' Altarianite','Enables Altaria to Mega Evolve during battle.'),
(' Ampharosite','Enables Ampharos to Mega Evolve during battle.'),
(' Amulet Coin','Doubles prize money if held.'),
(' Assault Vest','Raises Special Defense but prevents the use of status moves.'),
(' Audinite','Enables Audino to Mega Evolve during battle.'),
(' Banettite','Enables Banette to Mega Evolve during battle.'),
(' Beedrillite','Enables Beedrill to Mega Evolve during battle.'),
(' Berry Sweet','Evolves Milcery into Blueberry Flavor Alcremie.'),
(' Big Root','Recovers more HP from HP-stealing moves.'),
(' Binding Band','A band that increases the power of binding moves when held.'),
(' Black Belt','Increases the power of Fighting-type moves.'),
(' Black Glasses','Increases the power of Dark-type moves.'),
(' Black Sludge','A held item that gradually restores the HP of Poison-type Pokémon. It inflicts damage on all other types.'),
(' Blastoisinite','Enables Blastoise to Mega Evolve during battle.'),
(' Blazikenite','Enables Blaziken to Mega Evolve during battle.'),
(' Blunder Policy','Raises Speed sharply if its attack misses.'),
(' Bright Powder','Lowers the opponents accuracy.'),
(' Bug Gem','Increases the power of a Bug-type move only once.'),
(' Bug Memory','Changes Silvally and its move Multi-Attack to Bug type.'),
(' Buginium Z','Allows the use of Savage Spin-Out, the Bug type Z-Move.'),
(' Burn Drive','Changes Techno Blast to a Fire-type move when held by Genesect.'),
(' Cameruptite','Enables Camerupt to Mega Evolve during battle.'),
(' Cell Battery','A consumable battery. If the holder is hit by an Electric-type move, its Attack will rise.'),
(' Charcoal','Increases the power of Fire-type moves.'),
(' Charizardite X','Enables Charizard to Mega Evolve during battle.'),
(' Charizardite Y','Enables Charizard to Mega Evolve during battle.'),
(' Chill Drive','Changes Techno Blast to an Ice-type move when held by Genesect.'),
(' Chipped Pot','Evolves Sinistea into Polteageist.'),
(' Choice Band','Raises Attack, but only one move can be used.'),
(' Choice Scarf','Raises Speed, but only one move can be used.'),
(' Choice Specs','Raises Special Attack, but only one move can be used.'),
(' Cleanse Tag','An item to be held by a Pokémon. It helps keep wild Pokémon away if the holder is the first one in the party.'),
(' Clover Sweet','Evolves Milcery into Clover Flavor Alcremie.'),
(' Colress Machine','A special device that wrings out the potential of Pokémon. It is an imperfect prototype.'),
(' Cracked Pot','Evolves Sinistea into Polteageist.'),
(' Damp Rock','A Pokémon held item that extends the duration of the move Rain Dance used by the holder.'),
(' Dark Gem','Increases the power of a Dark-type move only once.'),
(' Dark Memory','Changes Silvally and its move Multi-Attack to Dark type.'),
(' Darkinium Z','Allows the use of Black Hole Eclipse, the Dark type Z-Move.'),
(' Decidium Z','Allows Decidueye to upgrade Spirit Shackle to a Z-Move, Sinister Arrow Raid.'),
(' Deep Sea Scale','Increases Special Defense when held by Clamperl. Evolves Clamperl when traded holding the item.'),
(' Deep Sea Tooth','Increases Special Attack when held by Clamperl. Evolves Clamperl when traded holding the item.'),
(' Destiny Knot','A long, thin, bright-red string to be held by a Pokémon. If the holder becomes infatuated, the foe does too.'),
(' Diancite','Enables Diancie to Mega Evolve during battle.'),
(' Douse Drive','Changes Techno Blast to a Water-type move when held by Genesect.'),
(' Draco Plate','Increases power of Dragon-type moves. Changes Arceus type to Dragon.'),
(' Dragon Fang','Increases the power of Dragon-type moves.'),
(' Dragon Gem','Increases the power of a Dragon-type move only once.'),
(' Dragon Memory','Changes Silvally and its move Multi-Attack to Dragon type.'),
(' Dragonium Z','Allows the use of Devastating Drake, the Dragon type Z-Move.'),
(' Dread Plate','Increases power of Dark-type moves. Changes Arceus type to Dark.'),
(' Dropped Item','The Xtransceiver found at the Nimbasa City amusement park. It seems it belongs to a boy.'),
(' Earth Plate','Increases power of Ground-type moves. Changes Arceus type to Ground.'),
(' Eevium Z','Allows Eevee to upgrade Last Resort to a Z-Move, Extreme Evoboost.'),
(' Eject Button','If the holder is hit by an attack, it will switch with another Pokémon in your party.'),
(' Eject Pack','The Pokémon switches out if its stats are lowered.'),
(' Electric Gem','Increases the power of an Electric-type move only once.'),
(' Electric Memory','Changes Silvally and its move Multi-Attack to Electric type.'),
(' Electric Seed','An item to be held by a Pokémon. It boosts Defense on Electric Terrain. It can only be used once.'),
(' Electrium Z','Allows the use of Gigavolt Havoc, the Electric type Z-Move.'),
(' Elevator Key','A card key that activates the elevator in Lysandre Labs. It is emblazoned with Team Flares logo.'),
(' Everstone','An item to be held by a Pokémon. The Pokémon holding this peculiar stone is prevented from evolving.'),
(' Eviolite','A mysterious evolutionary lump. When held, it raises the Defense and Sp. Def of a Pokémon that can still evolve.'),
(' Exp. Share','An item to be held by a Pokémon. The holder gets a share of a battles Exp. Points without battling.'),
(' Expert Belt','Increases the power of super-effective moves.'),
(' Fairium Z','Allows the use of Twinkle Tackle, the Fairy type Z-Move.'),
(' Fairy Memory','Changes Silvally and its move Multi-Attack to Fairy type.'),
(' Fighting Gem','Increases the power of a Fighting-type move only once.'),
(' Fighting Memory','Changes Silvally and its move Multi-Attack to Fighting type.'),
(' Fightinium Z','Allows the use of All-Out Pummeling, the Fighting type Z-Move.'),
(' Fire Gem','Increases the power of a Fire-type move only once.'),
(' Fire Memory','Changes Silvally and its move Multi-Attack to Fire type.'),
(' Firium Z','Allows the use of Inferno Overdrive, the Fire type Z-Move.'),
(' Fist Plate','Increases power of Fighting-type moves. Changes Arceus type to Fighting.'),
(' Flame Orb','An item to be held by a Pokémon. It is a bizarre orb that inflicts a burn on the holder in battle.'),
(' Flame Plate','Increases power of Fire-type moves. Changes Arceus type to Fire.'),
(' Float Stone','A very light stone. It reduces the weight of a Pokémon when held.'),
(' Flower Sweet','Evolves Milcery into Flower Flavor Alcremie.'),
(' Flying Gem','Increases the power of a Flying-type move only once.'),
(' Flying Memory','Changes Silvally and its move Multi-Attack to Flying type.'),
(' Flyinium Z','Allows the use of Supersonic Skystrike, the Flying type Z-Move.'),
(' Focus Band','An item to be held by a Pokémon. The holder may endure a potential KO attack, leaving it with just 1 HP.'),
(' Focus Sash','An item to be held by a Pokémon. If it has full HP, the holder will endure one potential KO attack, leaving 1 HP.'),
(' Full Incense','Holder always attacks last. Breeding Snorlax produces Munchlax when held.'),
(' Galladite','Enables Gallade to Mega Evolve during battle.'),
(' Garchompite','Enables Garchomp to Mega Evolve during battle.'),
(' Gardevoirite','Enables Gardevoir to Mega Evolve during battle.'),
(' Gengarite','Enables Gengar to Mega Evolve during battle.'),
(' Ghost Gem','Increases the power of a Ghost-type move only once.'),
(' Ghost Memory','Changes Silvally and its move Multi-Attack to Ghost type.'),
(' Ghostium Z','Allows the use of Never-Ending Nightmare, the Ghost type Z-Move.'),
(' Glalitite','Enables Glalie to Mega Evolve during battle.'),
(' Grass Gem','Increases the power of a Grass-type move only once.'),
(' Grass Memory','Changes Silvally and its move Multi-Attack to Grass type.'),
(' Grassium Z','Allows the use of Bloom Doom, the Grass type Z-Move.'),
(' Grassy Seed','An item to be held by a Pokémon. It boosts Defense on Grassy Terrain. It can only be used once.'),
(' Grip Claw','A Pokémon held item that extends the duration of multiturn attacks like Bind and Wrap.'),
(' Griseous Orb','Increases the power of Dragon- and Ghost-type moves when held by Giratina, and changes it to Origin Forme.'),
(' Ground Gem','Increases the power of a Ground-type move only once.'),
(' Ground Memory','Changes Silvally and its move Multi-Attack to Ground type.'),
(' Groundium Z','Allows the use of Tectonic Rage, the Ground type Z-Move.'),
(' Grubby Hanky','A handkerchief dropped by a regular at Café Warehouse. It smells faintly like a Pokémon.'),
(' Gyaradosite','Enables Gyarados to Mega Evolve during battle.'),
(' Hard Stone','Increases the power of Rock-type moves.'),
(' Heat Rock','A Pokémon held item that extends the duration of the move Sunny Day used by the holder.'),
(' Heavy-Duty Boots','Protects the holder from traps set on the battlefield.'),
(' Heracronite','Enables Heracross to Mega Evolve during battle.'),
(' Hi-tech Earbuds','Strange earbuds that allow you to freely control the volume of various sounds.'),
(' Honor Of Kalos','A precious symbol that is awarded only to an individual who has done great things for the Kalos region.'),
(' Houndoominite','Enables Houndoom to Mega Evolve during battle.'),
(' Ice Gem','Increases the power of an Ice-type move only once.'),
(' Ice Memory','Changes Silvally and its move Multi-Attack to Ice type.'),
(' Icicle Plate','Increases power of Ice-type moves. Changes Arceus type to Ice.'),
(' Icium Z','Allows the use of Subzero Slammer, the Ice type Z-Move.'),
(' Icy Rock','A Pokémon held item that extends the duration of the move Hail used by the holder.'),
(' Incinium Z','Allows Incineroar to upgrade Darkest Lariat to a Z-Move, Malicious Moonsault.'),
(' Insect Plate','Increases power of Bug-type moves. Changes Arceus type to Bug.'),
(' Intriguing Stone','A rather curious stone that might appear to be valuable to some. It is all in the eye of the beholder.'),
(' Iron Ball','A Pokémon held item that cuts Speed. It makes Flying-type and levitating holders susceptible to Ground moves.'),
(' Iron Plate','Increases power of Steel-type moves. Changes Arceus type to Steel.'),
(' Kangaskhanite','Enables Kangaskhan to Mega Evolve during battle.'),
(' Kings Rock','May cause opponent to flinch. Evolves Poliwhirl and Slowpoke when traded holding the item.'),
(' Kommonium Z','Allows Kommo-o to upgrade Clanging Scales to a Z-Move, Clangorous Soulblaze.'),
(' Lagging Tail','Holder always attacks last.'),
(' Latiasite','Enables Latias to Mega Evolve during battle.'),
(' Latiosite','Enables Latios to Mega Evolve during battle.'),
(' Lax Incense','Lowers the opponents accuracy. Breeding Wobbuffet produces Wynaut when held.'),
(' Leek','Increases critical-hit ratio when held by Farfetchd.'),
(' Leftovers','An item to be held by a Pokémon. The holders HP is gradually restored during battle.'),
(' Life Orb','Increases the power of moves, but loses HP each turn.'),
(' Light Ball','An item to be held by PIKACHU. It is a puzzling orb that raises the Attack and Sp. Atk stat.'),
(' Light Clay','A Pokémon held item that extends the duration of barrier moves like Light Screen and Reflect used by the holder.'),
(' Looker Ticket','A ticket that was handmade by Looker. It is decorated with a liberal amount of glittery paint.'),
(' Lopunnite','Enables Lopunny to Mega Evolve during battle.'),
(' Love Sweet','Evolves Milcery into Heart Flavor Alcremie.'),
(' Lucarionite','Enables Lucario to Mega Evolve during battle.'),
(' Luck Incense','Doubles prize money if held. Breeding Chansey or Blissey produces Happiny when held.'),
(' Lucky Egg','An item to be held by a Pokémon. It is an egg filled with happiness that earns extra Exp. Points in battle.'),
(' Lucky Punch','Increases critical-hit ratio when held by Chansey.'),
(' Luminous Moss','Raises Special Defense if hit by a Water-type move.'),
(' Lunalium Z','Allows Lunala to upgrade Moongeist Beam to a Z-Move, Menacing Moonraze Maelstrom.'),
(' Lustrous Orb','Increases the power of Dragon- and Water-type moves when held by Palkia.'),
(' Lycanium Z','Allows Lycanroc to upgrade Stone Edge to a Z-Move, Splintered Stormshards.'),
(' Macho Brace','An item to be held by a Pokémon. It is a stiff and heavy brace that promotes strong growth but lowers Speed.'),
(' Magnet','Increases the power of Electric-type moves.'),
(' Manectite','Enables Manectric to Mega Evolve during battle.'),
(' Marshadium Z','Allows Marshadow to upgrade Spectral Thief to a Z-Move, Soul-Stealing 7-Star Strike.'),
(' Mawilite','Enables Mawile to Mega Evolve during battle.'),
(' Meadow Plate','Increases power of Grass-type moves. Changes Arceus type to Grass.'),
(' Medichamite','Enables Medicham to Mega Evolve during battle.'),
(' Mental Herb','An item to be held by a Pokémon. It snaps the holder out of infatuation. It can be used only once.'),
(' Metagrossite','Enables Metagross to Mega Evolve during battle.'),
(' Metal Coat','Increases the power of Steel-type moves. Evolves Onix and Scyther when traded holding the item.'),
(' Metal Powder','Increases Defense when held by Ditto.'),
(' Metronome','Increases the power of moves used consecutively.'),
(' Mewnium Z','Allows Mew to upgrade Psychic to a Z-Move, Genesis Supernova.'),
(' Mewtwonite X','Enables Mewtwo to Mega Evolve during battle.'),
(' Mewtwonite Y','Enables Mewtwo to Mega Evolve during battle.'),
(' Mimikium Z','Allows Mimikyu to upgrade Play Rough to a Z-Move, Lets Snuggle Forever.'),
(' Mind Plate','Increases power of Psychic-type moves. Changes Arceus type to Psychic.'),
(' Miracle Seed','Increases the power of Grass-type moves.'),
(' Misty Seed','An item to be held by a Pokémon. It boosts Sp. Def on Misty Terrain. It can only be used once.'),
(' Muscle Band','Increases the power of Physical-category moves.'),
(' Mystic Water','Increases the power of Water-type moves.'),
(' Never-Melt Ice','Increases the power of Ice-type moves.'),
(' Normal Gem','Increases the power of a Normal-type move only once.'),
(' Normalium Z','Allows the use of Breakneck Blitz, the Normal type Z-Move.'),
(' Odd Incense','Increases the power of Psychic-type moves. Breeding Mr. Mime produces Mime Jr. when held.'),
(' Pass Orb','A mysterious orb containing the power of the Unova region, to be used when generating Pass Power.'),
(' Pidgeotite','Enables Pidgeot to Mega Evolve during battle.'),
(' Pikanium Z','Allows Pikachu to upgrade Volt Tackle to a Z-Move, Catastropika.'),
(' Pikashunium Z','Allows Pikachu in a cap to upgrade Thunderbolt to a Z-Move, 10,000,000 Volt Thunderbolt.'),
(' Pink Nectar','The flower nectar obtained at the flowering shrubs on Royal Avenue. It changes the form of certain species of Pokémon.'),
(' Pinsirite','Enables Pinsir to Mega Evolve during battle.'),
(' Pixie Plate','Increases power of Fairy-type moves. Changes Arceus type to Fairy.'),
(' Plasma Card','A card key needed to enter the password inside the Plasma Frigate.'),
(' Poison Barb','Increases the power of Poison-type moves.'),
(' Poison Gem','Increases the power of a Poison-type move only once.'),
(' Poison Memory','Changes Silvally and its move Multi-Attack to Poison type.'),
(' Poisonium Z','Allows the use of Acid Downpour, the Poison type Z-Move.'),
(' Power Anklet','A Pokémon held item that promotes Speed gain on leveling, but reduces the Speed stat.'),
(' Power Band','A Pokémon held item that promotes Sp. Def gain on leveling, but reduces the Speed stat.'),
(' Power Belt','A Pokémon held item that promotes Defense gain on leveling, but reduces the Speed stat.'),
(' Power Bracer','A Pokémon held item that promotes Attack gain on leveling, but reduces the Speed stat.'),
(' Power Herb','A single-use item to be held by a Pokémon. It allows the immediate use of a move that charges on the first turn.'),
(' Power Lens','A Pokémon held item that promotes Sp. Atk gain on leveling, but reduces the Speed stat.'),
(' Power Plant Pass','This pass serves as an ID card for gaining access to the power plant that lies along Route 13.'),
(' Power Weight','A Pokémon held item that promotes HP gain on leveling, but reduces the Speed stat.'),
(' Primarium Z','Allows Primarina to upgrade Sparkling Aria to a Z-Move, Oceanic Operetta.'),
(' Prison Bottle','Transforms Hoopa Confined to Hoopa Unbound.'),
(' Profs Letter','A letter that Professor Sycamore wrote to your mother. A faint but pleasant perfume seems to cling to the paper.'),
(' Protective Pads','An item to be held by a Pokémon. These pads protect the holder from effects caused by making direct contact with the target.'),
(' Psychic Gem','Increases the power of a Psychic-type move only once.'),
(' Psychic Memory','Changes Silvally and its move Multi-Attack to Psychic type.'),
(' Psychic Seed','An item to be held by a Pokémon. It boosts Sp. Def on Psychic Terrain. It can only be used once.'),
(' Psychium Z','Allows the use of Shattered Psyche, the Psychic type Z-Move.'),
(' Pure Incense','Descreases the likelihood of meeting wild Pokémon. Breeding Chimecho produces Chingling when held.'),
(' Purple Nectar','A flower nectar obtained at Poni Meadow. It changes the form of certain species of Pokémon.'),
(' Quick Claw','An item to be held by a Pokémon. A light, sharp claw that lets the bearer move first occasionally.'),
(' Quick Powder','Increases Speed when held by Ditto.'),
(' Razor Claw','Increases critical-hit ratio. Evolves Sneasel when held at night.'),
(' Razor Fang','May cause opponent to flinch. Evolves Gligar when held at night.'),
(' Red Card','A card with a mysterious power. When the holder is struck by a foe, the attacker is removed from battle.'),
(' Red Nectar','A flower nectar obtained at Ulaula Meadow. It changes the form of certain species of Pokémon.'),
(' Ribbon Sweet','Evolves Milcery into Ribbon Flavor Alcremie.'),
(' Ring Target','Moves that would otherwise have no effect will land on the Pokémon that holds it.'),
(' Rock Gem','Increases the power of a Rock-type move only once.'),
(' Rock Incense','Increases the power of Rock-type moves. Breeding Sudowoodo produces Bonsly when held.'),
(' Rock Memory','Changes Silvally and its move Multi-Attack to Rock type.'),
(' Rockium Z','Allows the use of Continental Crush, the Rock type Z-Move.'),
(' Rocky Helmet','If the holder of this item takes damage, the attacker will also be damaged upon contact.'),
(' Room Service','Lowers the Pokémons speed during Trick Room.'),
(' Rose Incense','Increases the power of Grass-type moves. Breeding Roselia or Roserade produces Budew when held.'),
(' Sablenite','Enables Sableye to Mega Evolve during battle.'),
(' Safety Goggles','Prevents damage from weather and powder.'),
(' Salamencite','Enables Salamence to Mega Evolve during battle.'),
(' Sceptilite','Enables Sceptile to Mega Evolve during battle.'),
(' Scizorite','Enables Scizor to Mega Evolve during battle.'),
(' Scope Lens','Increases critical-hit ratio.'),
(' Sea Incense','Increases the power of Water-type moves. Breeding Marill or Azumarill produces Azurill when held.'),
(' Sharp Beak','Increases the power of Flying-type moves.'),
(' Sharpedonite','Enables Sharpedo to Mega Evolve during battle.'),
(' Shed Shell','A tough, discarded carapace to be held by a Pokémon. It enables the holder to switch with a waiting Pokémon in battle.'),
(' Shell Bell','An item to be held by a Pokémon. The holders HP is restored a little every time it inflicts damage.'),
(' Shock Drive','Changes Techno Blast to an Electric-type move when held by Genesect.'),
(' Silk Scarf','Increases the power of Normal-type moves.'),
(' Silver Powder','Increases the power of Bug-type moves.'),
(' Sky Plate','Increases power of Flying-type moves. Changes Arceus type to Flying.'),
(' Slowbronite','Enables Slowbro to Mega Evolve during battle.'),
(' Smoke Ball','An item to be held by a Pokémon. It enables the holder to flee from any wild Pokémon without fail.'),
(' Smooth Rock','A Pokémon held item that extends the duration of the move Sandstorm used by the holder.'),
(' Snorlium Z','Allows Snorlax to upgrade Giga Impact to a Z-Move, Pulverizing Pancake.'),
(' Snowball','Raises Attack if hit by an Ice-type move.'),
(' Soft Sand','Increases the power of Ground-type moves.'),
(' Solganium Z','Allows Solgaleo to upgrade Sunsteel Strike to a Z-Move, Searing Sunraze Smash.'),
(' Soothe Bell','An item to be held by a Pokémon. It is a bell with a comforting chime that calms the holder and makes it friendly.'),
(' Soul Dew','Increases the power of Psychic- and Dragon-type moves when held by Latios or Latias. Increases Sp.Atk/Sp.Def prior to Gen 7.'),
(' Spell Tag','Increases the power of Ghost-type moves.'),
(' Splash Plate','Increases power of Water-type moves. Changes Arceus type to Water.'),
(' Spooky Plate','Increases power of Ghost-type moves. Changes Arceus type to Ghost.'),
(' Star Sweet','Evolves Milcery into Star Flavor Alcremie.'),
(' Steel Gem','Increases the power of a Steel-type move only once.'),
(' Steel Memory','Changes Silvally and its move Multi-Attack to Steel type.'),
(' Steelium Z','Allows the use of Corkscrew Crash, the Steel type Z-Move.'),
(' Steelixite','Enables Steelix to Mega Evolve during battle.'),
(' Sticky Barb','A held item that damages the holder on every turn. It may latch on to foes and allies that touch the holder.'),
(' Stone Plate','Increases power of Rock-type moves. Changes Arceus type to Rock.'),
(' Strawberry Sweet','Evolves Milcery into Strawberry Flavor Alcremie.'),
(' Swampertite','Enables Swampert to Mega Evolve during battle.'),
(' Sweet Apple','Evolves Applin into Appletun.'),
(' Tapunium Z','Allows the Tapus to upgrade Natures Madness to a Z-Move, Guardian of Alola.'),
(' Tart Apple','Evolves Applin into Flapple.'),
(' Terrain Extender','An item to be held by a Pokémon. It extends the duration of the terrain caused by the holders move or Ability.'),
(' Thick Club','Increases Attack when held by Cubone or Marowak.'),
(' Throat Spray','Raises Sp. Atk when a sound-based move is used.'),
(' Toxic Orb','An item to be held by a Pokémon. It is a bizarre orb that badly poisons the holder in battle.'),
(' Toxic Plate','Increases power of Poison-type moves. Changes Arceus type to Poison.'),
(' Twisted Spoon','Increases the power of Psychic-type moves.'),
(' Tyranitarite','Enables Tyranitar to Mega Evolve during battle.'),
(' Ultranecrozium Z','Allows Ultra Necrozma to upgrade Photon Geyser to a Z-Move, Light That Burns the Sky.'),
(' Utility Umbrella','An item to be held by a Pokémon. This sturdy umbrella protects the holder from the effects of weather.'),
(' Venusaurite','Enables Venusaur to Mega Evolve during battle.'),
(' Water Gem','Increases the power of a Water-type move only once.'),
(' Water Memory','Changes Silvally and its move Multi-Attack to Water type.'),
(' Waterium Z','Allows the use of Hydro Vortex, the Water type Z-Move.'),
(' Wave Incense','Increases the power of Water-type moves. Breeding Mantine produces Mantyke when held.'),
(' Weakness Policy','Sharply raises Attack and Special Attack if hit by a super-effective move.'),
(' White Herb','An item to be held by a POKéMON. It restores any lowered stat in battle. It can be used only once.'),
(' Wide Lens','Increases the accuracy of moves.'),
(' Wise Glasses','Increases the power of Special-category moves.'),
(' Yellow Nectar','A flower nectar obtained at Melemele Meadow. It changes the form of certain species of Pokémon.'),
(' Zap Plate','Increases power of Electric-type moves. Changes Arceus type to Electric.'),
(' Zoom Lens','Raises a moves accuracy if the holder moves after its target.');

SELECT * FROM HeldItem;


