--USE PokemonVGC;

--DROP TABLE IF EXISTS Ability;

CREATE TABLE Ability
(
abilityID INT NOT NULL IDENTITY
	CONSTRAINT PK_Ability PRIMARY KEY,
abilityName NVARCHAR (30),
abilityDescription NVARCHAR (200)
);
GO
/*
SET IDENTITY_INSERT Ability ON;
GO


INSERT INTO Ability (abilityID, abilityName, AbilityDescription)
VALUES
(1, 'Adaptability','Powers up moves of the same type.'),
(2, 'Aerilate','Turns Normal-type moves into Flying-type moves.'),
(3, 'Aftermath','Damages the attacker landing the finishing hit.'),
(4, 'Air Lock','Eliminates the effects of weather.'),
(5, 'Analytic','Boosts move power when the Pokémon moves last.'),
(6, 'Anger Point','Maxes Attack after taking a critical hit.'),
(7, 'Anticipation','Senses a foe''s dangerous moves.'),
(8, 'Arena Trap','Prevents the foe from fleeing.'),
(9, 'Aroma Veil','Protects allies from attacks that limit their move choices.'),
(10, 'Aura Break','Reduces power of Dark- and Fairy-type moves.'),
(11, 'Bad Dreams','Reduces a sleeping foe''s HP.'),
(12, 'Ball Fetch','Retrieves a Poké Ball from a failed throw.'),
(13, 'Battery','Raises power of teammates'' Special moves.'),
(14, 'Battle Armor','The Pokémon is protected against critical hits.'),
(15, 'Battle Bond','Transform into Ash-Greninja after causing opponent to faint.'),
(16, 'Beast Boost','The Pokémon boosts its most proficient stat each time it knocks out a Pokémon.'),
(17, 'Berserk','Raises Special Attack when HP drops below half.'),
(18, 'Big Pecks','Protects the Pokémon from Defense-lowering attacks.'),
(19, 'Blaze','Powers up Fire-type moves in a pinch.'),
(20, 'Bulletproof','Protects the Pokémon from ball and bomb moves.'),
(21, 'Cheek Pouch','Restores additional HP when a Berry is consumed.'),
(22, 'Chlorophyll','Boosts the Pokémon''s Speed in sunshine.'),
(23, 'Clear Body','Prevents other Pokémon from lowering its stats.'),
(24, 'Cloud Nine','Eliminates the effects of weather.'),
(25, 'Color Change','Changes the Pokémon''s type to the foe''s move.'),
(26, 'Comatose','The Pokémon is always asleep but can still attack.'),
(27, 'Competitive','Raises Special Attack when the Pokémon''s stats are lowered.'),
(28, 'Compound Eyes','The Pokémon''s accuracy is boosted.'),
(29, 'Contrary','Makes stat changes have an opposite effect.'),
(30, 'Corrosion','The Pokémon can poison Steel and Poison types.'),
(31, 'Cotton Down','Lowers foe''s Speed when hit.'),
(32, 'Cursed Body','May disable a move used on the Pokémon.'),
(33, 'Cute Charm','Contact with the Pokémon may cause infatuation.'),
(34, 'Damp','Prevents the use of self-destructing moves.'),
(35, 'Dancer','Copies the foe''s Dance moves.'),
(36, 'Dark Aura','Raises power of Dark type moves for all Pokémon in battle.'),
(37, 'Dauntless Shield','Boosts Defense in battle.'),
(38, 'Dazzling','Protects the Pokémon from high-priority moves.'),
(39, 'Defeatist','Lowers stats when HP drops below half.'),
(40, 'Defiant','When its stats are lowered its Attack increases.'),
(41, 'Delta Stream','Creates strong winds when the ability activates.'),
(42, 'Desolate Land','Turns the sunlight extremely harsh when the ability activates.'),
(43, 'Disguise','Avoids damage for one turn.'),
(44, 'Download','Adjusts power according to a foe''s defenses.'),
(45, 'Drizzle','The Pokémon makes it rain when it enters a battle.'),
(46, 'Drought','Turns the sunlight harsh when the Pokémon enters a battle.'),
(47, 'Dry Skin','Reduces HP if it is hot. Water restores HP.'),
(48, 'Early Bird','The Pokémon awakens quickly from sleep.'),
(49, 'Effect Spore','Contact may poison or cause paralysis or sleep.'),
(50, 'Electric Surge','The Pokémon creates an Electric Terrain when it enters a battle.'),
(51, 'Emergency Exit','Switches out when HP falls below 50%.'),
(52, 'Fairy Aura','Raises power of Fairy type moves for all Pokémon in battle.'),
(53, 'Filter','Reduces damage from super-effective attacks.'),
(54, 'Flame Body','Contact with the Pokémon may burn the attacker.'),
(55, 'Flare Boost','Powers up special attacks when burned.'),
(56, 'Flash Fire','It powers up Fire-type moves if it''s hit by one.'),
(57, 'Flower Gift','Powers up party Pokémon when it is sunny.'),
(58, 'Flower Veil','Prevents lowering of ally Grass-type Pokémon''s stats.'),
(59, 'Fluffy','Halves damage from contact moves, but doubles damage from Fire-type moves.'),
(60, 'Forecast','Castform transforms with the weather.'),
(61, 'Forewarn','Determines what moves a foe has.'),
(62, 'Friend Guard','Reduces damage done to allies.'),
(63, 'Frisk','The Pokémon can check a foe''s held item.'),
(64, 'Full Metal Body','Prevents other Pokémon from lowering its stats.'),
(65, 'Fur Coat','Reduces damage from physical moves.'),
(66, 'Gale Wings','Gives priority to Flying-type moves.'),
(67, 'Galvanize','Normal-type moves become Electric-type moves and their power boosted.'),
(68, 'Gluttony','Encourages the early use of a held Berry.'),
(69, 'Gooey','Contact with the Pokémon lowers the attacker''s Speed stat.'),
(70, 'Gorilla Tactics','Boosts the Pokémon''s Attack stat but only allows the use of the first selected move.'),
(71, 'Grass Pelt','Boosts the Defense stat in Grassy Terrain.'),
(72, 'Grassy Surge','The Pokémon creates a Grassy Terrain when it enters a battle.'),
(73, 'Gulp Missile','Returns with a catch in its mouth after using Surf or Dive.'),
(74, 'Guts','Boosts Attack if there is a status problem.'),
(75, 'Harvest','May create another Berry after one is used.'),
(76, 'Healer','May heal an ally''s status conditions.'),
(77, 'Heatproof','Weakens the power of Fire-type moves.'),
(78, 'Heavy Metal','Doubles the Pokémon''s weight.'),
(79, 'Honey Gather','The Pokémon may gather Honey from somewhere.'),
(80, 'Huge Power','Raises the Pokémon''s Attack stat.'),
(81, 'Hunger Switch','Changes forms each turn.'),
(82, 'Hustle','Boosts the Attack stat, but lowers accuracy.'),
(83, 'Hydration','Heals status problems if it is raining.'),
(84, 'Hyper Cutter','Prevents other Pokémon from lowering Attack stat.'),
(85, 'Ice Body','The Pokémon gradually regains HP in a hailstorm.'),
(86, 'Ice Face','Avoids damage from Physical moves for one turn.'),
(87, 'Ice Scales','Halves damage from Special moves.'),
(88, 'Illuminate','Raises the likelihood of meeting wild Pokémon.'),
(89, 'Illusion','Enters battle disguised as the last Pokémon in the party.'),
(90, 'Immunity','Prevents the Pokémon from getting poisoned.'),
(91, 'Imposter','It transforms itself into the Pokémon it is facing.'),
(92, 'Infiltrator','Passes through the foe''s barrier and strikes.'),
(93, 'Innards Out','Deals damage upon fainting.'),
(94, 'Inner Focus','The Pokémon is protected from flinching.'),
(95, 'Insomnia','Prevents the Pokémon from falling asleep.'),
(96, 'Intimidate','Lowers the foe''s Attack stat.'),
(97, 'Intrepid Sword','Boosts Attack in battle.'),
(98, 'Iron Barbs','Inflicts damage to the Pokémon on contact.'),
(99, 'Iron Fist','Boosts the power of punching moves.'),
(100, 'Justified','Raises Attack when hit by a Dark-type move.'),
(101, 'Keen Eye','Prevents other Pokémon from lowering accuracy.'),
(102, 'Klutz','The Pokémon can''t use any held items.'),
(103, 'Leaf Guard','Prevents problems with status in sunny weather.'),
(104, 'Levitate','Gives immunity to Ground type moves.'),
(105, 'Libero','Changes the Pokémon''s type to its last used move.'),
(106, 'Light Metal','Halves the Pokémon''s weight.'),
(107, 'Lightning Rod','Draws in all Electric-type moves to up Sp. Attack.'),
(108, 'Limber','The Pokémon is protected from paralysis.'),
(109, 'Liquid Ooze','Damages attackers using any draining move.'),
(110, 'Liquid Voice','All sound-based moves become Water-type moves.'),
(111, 'Long Reach','The Pokémon uses its moves without making contact with the target.'),
(112, 'Magic Bounce','Reflects status- changing moves.'),
(113, 'Magic Guard','Protects the Pokémon from indirect damage.'),
(114, 'Magician','The Pokémon steals the held item of a Pokémon it hits with a move.'),
(115, 'Magma Armor','Prevents the Pokémon from becoming frozen.'),
(116, 'Magnet Pull','Prevents Steel-type Pokémon from escaping.'),
(117, 'Marvel Scale','Ups Defense if there is a status problem.'),
(118, 'Mega Launcher','Boosts the power of aura and pulse moves.'),
(119, 'Merciless','The Pokémon''s attacks become critical hits if the target is poisoned.'),
(120, 'Mimicry','Changes type depending on the terrain.'),
(121, 'Minus','Ups Sp. Atk if another Pokémon has Plus or Minus.'),
(122, 'Mirror Armor','Reflects any stat-lowering effects.'),
(123, 'Misty Surge','The Pokémon creates a Misty Terrain when it enters a battle.'),
(124, 'Mold Breaker','Moves can be used regardless of Abilities.'),
(125, 'Moody','Raises one stat and lowers another.'),
(126, 'Motor Drive','Raises Speed if hit by an Electric-type move.'),
(127, 'Moxie','Boosts Attack after knocking out any Pokémon.'),
(128, 'Multiscale','Reduces damage when HP is full.'),
(129, 'Multitype','Changes type to match the held Plate.'),
(130, 'Mummy','Contact with this Pokémon spreads this Ability.'),
(131, 'Natural Cure','All status problems heal when it switches out.'),
(132, 'Neuroforce','Powers up moves that are super effective.'),
(133, 'Neutralizing Gas','Neutralizes abilities of all Pokémon in battle.'),
(134, 'No Guard','Ensures attacks by or against the Pokémon land.'),
(135, 'Normalize','All the Pokémon''s moves become the Normal type.'),
(136, 'Oblivious','Prevents it from becoming infatuated.'),
(137, 'Overcoat','Protects the Pokémon from weather damage.'),
(138, 'Overgrow','Powers up Grass-type moves in a pinch.'),
(139, 'Own Tempo','Prevents the Pokémon from becoming confused.'),
(140, 'Parental Bond','Allows the Pokémon to attack twice.'),
(141, 'Pastel Veil','Prevents the Pokémon and its allies from being poisoned.'),
(142, 'Perish Body','When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle.'),
(143, 'Pickpocket','Steals an item when hit by another Pokémon.'),
(144, 'Pickup','The Pokémon may pick up items.'),
(145, 'Pixilate','Turns Normal-type moves into Fairy-type moves.'),
(146, 'Plus','Ups Sp. Atk if another Pokémon has Plus or Minus.'),
(147, 'Poison Heal','Restores HP if the Pokémon is poisoned.'),
(148, 'Poison Point','Contact with the Pokémon may poison the attacker.'),
(149, 'Poison Touch','May poison targets when a Pokémon makes contact.'),
(150, 'Power Construct','Changes form when HP drops below half.'),
(151, 'Power of Alchemy','The Pokémon copies the Ability of a defeated ally.'),
(152, 'Power Spot','Just being next to the Pokémon powers up moves.'),
(153, 'Prankster','Gives priority to a status move.'),
(154, 'Pressure','The Pokémon raises the foe''s PP usage.'),
(155, 'Primordial Sea','Makes it rain heavily when the ability activates.'),
(156, 'Prism Armor','Reduces damage from super-effective attacks.'),
(157, 'Propeller Tail','Ignores moves and abilities that draw in moves.'),
(158, 'Protean','Changes the Pokémon''s type to its last used move.'),
(159, 'Psychic Surge','The Pokémon creates a Psychic Terrain when it enters a battle.'),
(160, 'Punk Rock','Boosts sound-based moves and halves damage from the same moves.'),
(161, 'Pure Power','Raises the Pokémon''s Attack stat.'),
(162, 'Queenly Majesty','Prevents use of priority moves.'),
(163, 'Quick Feet','Boosts Speed if there is a status problem.'),
(164, 'Rain Dish','The Pokémon gradually regains HP in rain.'),
(165, 'Rattled','Bug, Ghost or Dark type moves scare it and boost its Speed.'),
(166, 'Receiver','Inherits an ally''s ability when it faints.'),
(167, 'Reckless','Powers up moves that have recoil damage.'),
(168, 'Refrigerate','Turns Normal-type moves into Ice-type moves.'),
(169, 'Regenerator','Restores a little HP when withdrawn from battle.'),
(170, 'Ripen','Doubles the effect of berries.'),
(171, 'Rivalry','Deals more damage to a Pokémon of same gender.'),
(172, 'RKS System','Changes type depending on held item.'),
(173, 'Rock Head','Protects the Pokémon from recoil damage.'),
(174, 'Rough Skin','Inflicts damage to the attacker on contact.'),
(175, 'Run Away','Enables a sure getaway from wild Pokémon.'),
(176, 'Sand Force','Boosts certain moves'' power in a sandstorm.'),
(177, 'Sand Rush','Boosts the Pokémon''s Speed in a sandstorm.'),
(178, 'Sand Spit','Creates a sandstorm when hit by an attack.'),
(179, 'Sand Stream','The Pokémon summons a sandstorm in battle.'),
(180, 'Sand Veil','Boosts the Pokémon''s evasion in a sandstorm.'),
(181, 'Sap Sipper','Boosts Attack when hit by a Grass-type move.'),
(182, 'Schooling','Changes Wishiwashi to School Form.'),
(183, 'Scrappy','Enables moves to hit Ghost-type Pokémon.'),
(184, 'Screen Cleaner','Nullifies effects of Light Screen, Reflect, and Aurora Veil.'),
(185, 'Serene Grace','Boosts the likelihood of added effects appearing.'),
(186, 'Shadow Shield','Reduces damage when HP is full.'),
(187, 'Shadow Tag','Prevents the foe from escaping.'),
(188, 'Shed Skin','The Pokémon may heal its own status problems.'),
(189, 'Sheer Force','Removes added effects to increase move damage.'),
(190, 'Shell Armor','The Pokémon is protected against critical hits.'),
(191, 'Shield Dust','Blocks the added effects of attacks taken.'),
(192, 'Shields Down','Changes stats when HP drops below half.'),
(193, 'Simple','Doubles all stat changes.'),
(194, 'Skill Link','Increases the frequency of multi-strike moves.'),
(195, 'Slow Start','Temporarily halves Attack and Speed.'),
(196, 'Slush Rush','Boosts the Pokémon''s Speed stat in a hailstorm.'),
(197, 'Sniper','Powers up moves if they become critical hits.'),
(198, 'Snow Cloak','Raises evasion in a hailstorm.'),
(199, 'Snow Warning','The Pokémon summons a hailstorm in battle.'),
(200, 'Solar Power','In sunshine, Sp. Atk is boosted but HP decreases.'),
(201, 'Solid Rock','Reduces damage from super-effective attacks.'),
(202, 'Soul-Heart','Raises Special Attack when an ally faints.'),
(203, 'Soundproof','Gives immunity to sound-based moves.'),
(204, 'Speed Boost','Its Speed stat is gradually boosted.'),
(205, 'Stakeout','Deals double damage to Pokémon switching in.'),
(206, 'Stall','The Pokémon moves after all other Pokémon do.'),
(207, 'Stalwart','Ignores moves and abilities that draw in moves.'),
(208, 'Stamina','Raises Defense when attacked.'),
(209, 'Stance Change','Changes form depending on moves used.'),
(210, 'Static','Contact with the Pokémon may cause paralysis.'),
(211, 'Steadfast','Raises Speed each time the Pokémon flinches.'),
(212, 'Steam Engine','Drastically raises Speed when hit by a Fire- or Water-type move.'),
(213, 'Steelworker','Powers up Steel-type moves.'),
(214, 'Steely Spirit','Powers up ally Pokémon''s Steel-type moves.'),
(215, 'Stench','The stench may cause the target to flinch.'),
(216, 'Sticky Hold','Protects the Pokémon from item theft.'),
(217, 'Storm Drain','Draws in all Water-type moves to up Sp. Attack.'),
(218, 'Strong Jaw','Boosts the power of biting moves.'),
(219, 'Sturdy','It cannot be knocked out with one hit.'),
(220, 'Suction Cups','Negates all moves that force switching out.'),
(221, 'Super Luck','Heightens the critical-hit ratios of moves.'),
(222, 'Surge Surfer','Doubles Speed during Electric Terrain.'),
(223, 'Swarm','Powers up Bug-type moves in a pinch.'),
(224, 'Sweet Veil','Prevents the Pokémon and allies from falling asleep.'),
(225, 'Swift Swim','Boosts the Pokémon''s Speed in rain.'),
(226, 'Symbiosis','The Pokémon can pass an item to an ally.'),
(227, 'Synchronize','Passes a burn, poison, or paralysis to the foe.'),
(228, 'Tangled Feet','Raises evasion if the Pokémon is confused.'),
(229, 'Tangling Hair','Contact with the Pokémon lowers the attacker''s Speed stat.'),
(230, 'Technician','Powers up the Pokémon''s weaker moves.'),
(231, 'Telepathy','Anticipates an ally''s attack and dodges it.'),
(232, 'Teravolt','Moves can be used regardless of Abilities.'),
(233, 'Thick Fat','Ups resistance to Fire- and Ice-type moves.'),
(234, 'Tinted Lens','Powers up “not very effective” moves.'),
(235, 'Torrent','Powers up Water-type moves in a pinch.'),
(236, 'Tough Claws','Boosts the power of contact moves.'),
(237, 'Toxic Boost','Powers up physical attacks when poisoned.'),
(238, 'Trace','The Pokémon copies a foe''s Ability.'),
(239, 'Triage','Gives priority to restorative moves.'),
(240, 'Truant','Pokémon can''t attack on consecutive turns.'),
(241, 'Turboblaze','Moves can be used regardless of Abilities.'),
(242, 'Unaware','Ignores any stat changes in the Pokémon.'),
(243, 'Unburden','Raises Speed if a held item is used.'),
(244, 'Unnerve','Makes the foe nervous and unable to eat Berries.'),
(245, 'Victory Star','Boosts the accuracy of its allies and itself.'),
(246, 'Vital Spirit','Prevents the Pokémon from falling asleep.'),
(247, 'Volt Absorb','Restores HP if hit by an Electric-type move.'),
(248, 'Wandering Spirit','Swaps abilities with opponents on contact.'),
(249, 'Water Absorb','Restores HP if hit by a Water-type move.'),
(250, 'Water Bubble','Halves damage from Fire-type moves, doubles power of Water-type moves used, and prevents burns.'),
(251, 'Water Compaction','Sharply raises Defense when hit by a Water-type move.'),
(252, 'Water Veil','Prevents the Pokémon from getting a burn.'),
(253, 'Weak Armor','Physical attacks lower Defense and raise Speed.'),
(254, 'White Smoke','Prevents other Pokémon from lowering its stats.'),
(255, 'Wimp Out','Switches out when HP drops below half.'),
(256, 'Wonder Guard','Only supereffective moves will hit.'),
(257, 'Wonder Skin','Makes status-changing moves more likely to miss.'),
(258, 'Zen Mode','Changes form when HP drops below half.');
GO

SET IDENTITY_INSERT Ability OFF;
GO

--SELECT * FROM Ability;
GO

*/