--USE PokemonVGC;

--DROP TABLE IF EXISTS HeldItem;

CREATE TABLE HeldItem
(
itemID INT NOT NULL IDENTITY
	CONSTRAINT PK_HeldItem PRIMARY KEY,
itemName NVARCHAR (30),
itemEffect NVARCHAR (300),
itemCat NVARCHAR (15),
);
GO
/*
SELECT * FROM HeldItem;

INSERT INTO HeldItem (itemCat, itemName, itemEffect)
VALUES
('Berries', 'Aguav Berry','Restores HP if it''s low, but may cause confusion.'),
('Berries', 'Apicot Berry','Raises Special Defense when HP is low.'),
('Berries', 'Aspear Berry','If held by a Pokémon, it defrosts it.'),
('Berries', 'Babiri Berry','Weakens a supereffective Steel-type attack against the holding Pokémon.'),
('Berries', 'Belue Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
('Berries', 'Bluk Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
('Berries', 'Charti Berry','Weakens a supereffective Rock-type attack against the holding Pokémon.'),
('Berries', 'Cheri Berry','If held by a Pokémon, it recovers from paralysis.'),
('Berries', 'Chesto Berry','If held by a Pokémon, it recovers from sleep.'),
('Berries', 'Chilan Berry','Weakens a Normal-type attack against the Pokémon holding this berry.'),
('Berries', 'Chople Berry','Weakens a supereffective Fighting-type attack against the holding Pokémon.'),
('Berries', 'Coba Berry','Weakens a supereffective Flying-type attack against the holding Pokémon.'),
('Berries', 'Colbur Berry','Weakens a supereffective Dark-type attack against the holding Pokémon.'),
('Berries', 'Cornn Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
('Berries', 'Custap Berry','Holder can move first when HP is low.'),
('Berries', 'Durin Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
('Berries', 'Enigma Berry','If held by a Pokémon, it restores its HP if it is hit by any supereffective attack.'),
('Berries', 'Figy Berry','Restores HP if it''s low, but may cause confusion.'),
('Berries', 'Ganlon Berry','Raises Defense when HP is low.'),
('Berries', 'Golden Nanab Berry','Drastically calms a Pokémon in battle, in Let''s Go Pikachu/Eevee.'),
('Berries', 'Golden Pinap Berry','Drastically increases chance of getting items when a Pokémon is caught, in Pokémon Let''s Go.'),
('Berries', 'Golden Razz Berry','Makes a Pokémon easier to catch in Pokémon Let''s Go.'),
('Berries', 'Grepa Berry','Increases Friendship but lowers Special Defense EVs.'),
('Berries', 'Haban Berry','Weakens a supereffective Dragon-type attack against the holding Pokémon.'),
('Berries', 'Hondew Berry','Increases Friendship but lowers Special Attack EVs.'),
('Berries', 'Iapapa Berry','Restores HP if it''s low, but may cause confusion.'),
('Berries', 'Jaboca Berry','If held by a Pokémon and a physical attack lands, the attacker also takes damage.'),
('Berries', 'Kasib Berry','Weakens a supereffective Ghost-type attack against the holding Pokémon.'),
('Berries', 'Kebia Berry','Weakens a supereffective Poison-type attack against the holding Pokémon.'),
('Berries', 'Kee Berry','If held by a Pokémon, this Berry will increase the holder''s Defense if it''s hit with a physical move.'),
('Berries', 'Kelpsy Berry','Increases Friendship but lowers Attack EVs.'),
('Berries', 'Lansat Berry','Increases critical-hit ratio when HP is low.'),
('Berries', 'Leppa Berry','If held by a Pokémon, it restores a move''s PP by 10.'),
('Berries', 'Liechi Berry','Raises Attack when HP is low.'),
('Berries', 'Lum Berry','If held by a Pokémon, it recovers from any status problem.'),
('Berries', 'Mago Berry','Restores HP if it''s low, but may cause confusion.'),
('Berries', 'Magost Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
('Berries', 'Maranga Berry','If held by a Pokémon, this Berry will increase the holder''s Sp. Def if it''s hit with a special move.'),
('Berries', 'Micle Berry','Increases a move''s accuracy when HP is low.'),
('Berries', 'Nanab Berry','A Berry to be used in cooking. Calms a Pokémon in battle, in Let''s Go Pikachu/Eevee.'),
('Berries', 'Nomel Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
('Berries', 'Occa Berry','Weakens a supereffective Fire-type attack against the holding Pokémon.'),
('Berries', 'Oran Berry','If held by a Pokémon, it heals the user by just 10 HP.'),
('Berries', 'Pamtre Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
('Berries', 'Passho Berry','Weakens a supereffective Water-type attack against the holding Pokémon.'),
('Berries', 'Payapa Berry','Weakens a supereffective Psychic-type attack against the holding Pokémon.'),
('Berries', 'Pecha Berry','If held by a Pokémon, it recovers from poison.'),
('Berries', 'Persim Berry','If held by a Pokémon, it recovers from confusion.'),
('Berries', 'Petaya Berry','Raises Special Attack when HP is low.'),
('Berries', 'Pinap Berry','A Berry to be used in cooking. Increases chances of getting items when a Pokémon is caught, in Pokémon Let''s Go.'),
('Berries', 'Pomeg Berry','Increases Friendship but lowers HP EVs.'),
('Berries', 'Qualot Berry','Increases Friendship but lowers Defense EVs.'),
('Berries', 'Rabuta Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
('Berries', 'Rawst Berry','If held by a Pokémon, it recovers from a burn.'),
('Berries', 'Razz Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
('Berries', 'Rindo Berry','Weakens a supereffective Grass-type attack against the holding Pokémon.'),
('Berries', 'Roseli Berry','If held by a Pokémon, this Berry will lessen the damage taken from one supereffective Fairy-type attack.'),
('Berries', 'Rowap Berry','If held by a Pokémon and a special attack lands, the attacker also takes damage.'),
('Berries', 'Salac Berry','Raises Speed when HP is low.'),
('Berries', 'Shuca Berry','Weakens a supereffective Ground-type attack against the holding Pokémon.'),
('Berries', 'Silver Nanab Berry','Greatly calms a Pokémon in battle, in Let''s Go Pikachu/Eevee.'),
('Berries', 'Silver Pinap Berry','Greatly increases chance of getting items when a Pokémon is caught, in Pokémon Let''s Go.'),
('Berries', 'Silver Razz Berry','Makes a Pokémon easier to catch in Pokémon Let''s Go.'),
('Berries', 'Sitrus Berry','If held by a Pokémon, it heals the user''s HP a little.'),
('Berries', 'Spelon Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
('Berries', 'Starf Berry','Sharply raises a random stat when HP is low.'),
('Berries', 'Tamato Berry','Increases Friendship but lowers Speed EVs.'),
('Berries', 'Tanga Berry','Weakens a supereffective Bug-type attack against the holding Pokémon.'),
('Berries', 'Wacan Berry','Weakens a supereffective Electric-type attack against the holding Pokémon.'),
('Berries', 'Watmel Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
('Berries', 'Wepear Berry','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
('Berries', 'Wiki Berry','Restores HP if it''s low, but may cause confusion.'),
('Berries', 'Yache Berry','Weakens a supereffective Ice-type attack against the holding Pokémon.'),
('Hold items', 'Ability Capsule','A capsule that allows a Pokémon with two Abilities to switch between these Abilities when it is used.'),
('Hold items', 'Abomasite','Enables Abomasnow to Mega Evolve during battle.'),
('Hold items', 'Absolite','Enables Absol to Mega Evolve during battle.'),
('Hold items', 'Absorb Bulb','A consumable bulb. If the holder is hit by a Water-type move, its Sp. Atk will rise.'),
('Hold items', 'Adamant Orb','Increases the power of Dragon- and Steel-type moves when held by Dialga.'),
('Hold items', 'Adrenaline Orb','Using it makes wild Pokémon more likely to call for help. If held by a Pokémon, it boosts Speed when intimidated. It can be used only once.'),
('Hold items', 'Aerodactylite','Enables Aerodactyl to Mega Evolve during battle.'),
('Hold items', 'Aggronite','Enables Aggron to Mega Evolve during battle.'),
('Hold items', 'Air Balloon','When held by a Pokémon, the Pokémon will float into the air. When the holder is attacked, this item will burst.'),
('Hold items', 'Alakazite','Enables Alakazam to Mega Evolve during battle.'),
('Hold items', 'Aloraichium Z','Allows Alolan Raichu to upgrade Thunderbolt to a Z-Move, Stoked Sparksurfer.'),
('Hold items', 'Altarianite','Enables Altaria to Mega Evolve during battle.'),
('Hold items', 'Ampharosite','Enables Ampharos to Mega Evolve during battle.'),
('Hold items', 'Amulet Coin','Doubles prize money if held.'),
('Hold items', 'Assault Vest','Raises Special Defense but prevents the use of status moves.'),
('Hold items', 'Audinite','Enables Audino to Mega Evolve during battle.'),
('Hold items', 'Banettite','Enables Banette to Mega Evolve during battle.'),
('Hold items', 'Beedrillite','Enables Beedrill to Mega Evolve during battle.'),
('Hold items', 'Berry Sweet','Evolves Milcery into Blueberry Flavor Alcremie.'),
('Hold items', 'Big Root','Recovers more HP from HP-stealing moves.'),
('Hold items', 'Binding Band','A band that increases the power of binding moves when held.'),
('Hold items', 'Black Belt','Increases the power of Fighting-type moves.'),
('Hold items', 'Black Glasses','Increases the power of Dark-type moves.'),
('Hold items', 'Black Sludge','A held item that gradually restores the HP of Poison-type Pokémon. It inflicts damage on all other types.'),
('Hold items', 'Blastoisinite','Enables Blastoise to Mega Evolve during battle.'),
('Hold items', 'Blazikenite','Enables Blaziken to Mega Evolve during battle.'),
('Hold items', 'Blunder Policy','Raises Speed sharply if its attack misses.'),
('Hold items', 'Bright Powder','Lowers the opponent''s accuracy.'),
('Hold items', 'Bug Gem','Increases the power of a Bug-type move only once.'),
('Hold items', 'Bug Memory','Changes Silvally and its move Multi-Attack to Bug type.'),
('Hold items', 'Buginium Z','Allows the use of Savage Spin-Out, the Bug type Z-Move.'),
('Hold items', 'Burn Drive','Changes Techno Blast to a Fire-type move when held by Genesect.'),
('Hold items', 'Cameruptite','Enables Camerupt to Mega Evolve during battle.'),
('Hold items', 'Cell Battery','A consumable battery. If the holder is hit by an Electric-type move, its Attack will rise.'),
('Hold items', 'Charcoal','Increases the power of Fire-type moves.'),
('Hold items', 'Charizardite X','Enables Charizard to Mega Evolve during battle.'),
('Hold items', 'Charizardite Y','Enables Charizard to Mega Evolve during battle.'),
('Hold items', 'Chill Drive','Changes Techno Blast to an Ice-type move when held by Genesect.'),
('Hold items', 'Chipped Pot','Evolves Sinistea into Polteageist.'),
('Hold items', 'Choice Band','Raises Attack, but only one move can be used.'),
('Hold items', 'Choice Scarf','Raises Speed, but only one move can be used.'),
('Hold items', 'Choice Specs','Raises Special Attack, but only one move can be used.'),
('Hold items', 'Cleanse Tag','An item to be held by a Pokémon. It helps keep wild Pokémon away if the holder is the first one in the party.'),
('Hold items', 'Clover Sweet','Evolves Milcery into Clover Flavor Alcremie.'),
('Hold items', 'Colress Machine','A special device that wrings out the potential of Pokémon. It is an imperfect prototype.'),
('Hold items', 'Cracked Pot','Evolves Sinistea into Polteageist.'),
('Hold items', 'Damp Rock','A Pokémon held item that extends the duration of the move Rain Dance used by the holder.'),
('Hold items', 'Dark Gem','Increases the power of a Dark-type move only once.'),
('Hold items', 'Dark Memory','Changes Silvally and its move Multi-Attack to Dark type.'),
('Hold items', 'Darkinium Z','Allows the use of Black Hole Eclipse, the Dark type Z-Move.'),
('Hold items', 'Decidium Z','Allows Decidueye to upgrade Spirit Shackle to a Z-Move, Sinister Arrow Raid.'),
('Hold items', 'Deep Sea Scale','Increases Special Defense when held by Clamperl. Evolves Clamperl when traded holding the item.'),
('Hold items', 'Deep Sea Tooth','Increases Special Attack when held by Clamperl. Evolves Clamperl when traded holding the item.'),
('Hold items', 'Destiny Knot','A long, thin, bright-red string to be held by a Pokémon. If the holder becomes infatuated, the foe does too.'),
('Hold items', 'Diancite','Enables Diancie to Mega Evolve during battle.'),
('Hold items', 'Douse Drive','Changes Techno Blast to a Water-type move when held by Genesect.'),
('Hold items', 'Draco Plate','Increases power of Dragon-type moves. Changes Arceus'' type to Dragon.'),
('Hold items', 'Dragon Fang','Increases the power of Dragon-type moves.'),
('Hold items', 'Dragon Gem','Increases the power of a Dragon-type move only once.'),
('Hold items', 'Dragon Memory','Changes Silvally and its move Multi-Attack to Dragon type.'),
('Hold items', 'Dragonium Z','Allows the use of Devastating Drake, the Dragon type Z-Move.'),
('Hold items', 'Dread Plate','Increases power of Dark-type moves. Changes Arceus'' type to Dark.'),
('Hold items', 'Dropped Item','The Xtransceiver found at the Nimbasa City amusement park. It seems it belongs to a boy.'),
('Hold items', 'Earth Plate','Increases power of Ground-type moves. Changes Arceus'' type to Ground.'),
('Hold items', 'Eevium Z','Allows Eevee to upgrade Last Resort to a Z-Move, Extreme Evoboost.'),
('Hold items', 'Eject Button','If the holder is hit by an attack, it will switch with another Pokémon in your party.'),
('Hold items', 'Eject Pack','The Pokémon switches out if its stats are lowered.'),
('Hold items', 'Electric Gem','Increases the power of an Electric-type move only once.'),
('Hold items', 'Electric Memory','Changes Silvally and its move Multi-Attack to Electric type.'),
('Hold items', 'Electric Seed','An item to be held by a Pokémon. It boosts Defense on Electric Terrain. It can only be used once.'),
('Hold items', 'Electrium Z','Allows the use of Gigavolt Havoc, the Electric type Z-Move.'),
('Hold items', 'Elevator Key','A card key that activates the elevator in Lysandre Labs. It is emblazoned with Team Flare''s logo.'),
('Hold items', 'Everstone','An item to be held by a Pokémon. The Pokémon holding this peculiar stone is prevented from evolving.'),
('Hold items', 'Eviolite','A mysterious evolutionary lump. When held, it raises the Defense and Sp. Def of a Pokémon that can still evolve.'),
('Hold items', 'Exp. Share','An item to be held by a Pokémon. The holder gets a share of a battle''s Exp. Points without battling.'),
('Hold items', 'Expert Belt','Increases the power of super-effective moves.'),
('Hold items', 'Fairium Z','Allows the use of Twinkle Tackle, the Fairy type Z-Move.'),
('Hold items', 'Fairy Memory','Changes Silvally and its move Multi-Attack to Fairy type.'),
('Hold items', 'Fighting Gem','Increases the power of a Fighting-type move only once.'),
('Hold items', 'Fighting Memory','Changes Silvally and its move Multi-Attack to Fighting type.'),
('Hold items', 'Fightinium Z','Allows the use of All-Out Pummeling, the Fighting type Z-Move.'),
('Hold items', 'Fire Gem','Increases the power of a Fire-type move only once.'),
('Hold items', 'Fire Memory','Changes Silvally and its move Multi-Attack to Fire type.'),
('Hold items', 'Firium Z','Allows the use of Inferno Overdrive, the Fire type Z-Move.'),
('Hold items', 'Fist Plate','Increases power of Fighting-type moves. Changes Arceus'' type to Fighting.'),
('Hold items', 'Flame Orb','An item to be held by a Pokémon. It is a bizarre orb that inflicts a burn on the holder in battle.'),
('Hold items', 'Flame Plate','Increases power of Fire-type moves. Changes Arceus'' type to Fire.'),
('Hold items', 'Float Stone','A very light stone. It reduces the weight of a Pokémon when held.'),
('Hold items', 'Flower Sweet','Evolves Milcery into Flower Flavor Alcremie.'),
('Hold items', 'Flying Gem','Increases the power of a Flying-type move only once.'),
('Hold items', 'Flying Memory','Changes Silvally and its move Multi-Attack to Flying type.'),
('Hold items', 'Flyinium Z','Allows the use of Supersonic Skystrike, the Flying type Z-Move.'),
('Hold items', 'Focus Band','An item to be held by a Pokémon. The holder may endure a potential KO attack, leaving it with just 1 HP.'),
('Hold items', 'Focus Sash','An item to be held by a Pokémon. If it has full HP, the holder will endure one potential KO attack, leaving 1 HP.'),
('Hold items', 'Full Incense','Holder always attacks last. Breeding Snorlax produces Munchlax when held.'),
('Hold items', 'Galladite','Enables Gallade to Mega Evolve during battle.'),
('Hold items', 'Garchompite','Enables Garchomp to Mega Evolve during battle.'),
('Hold items', 'Gardevoirite','Enables Gardevoir to Mega Evolve during battle.'),
('Hold items', 'Gengarite','Enables Gengar to Mega Evolve during battle.'),
('Hold items', 'Ghost Gem','Increases the power of a Ghost-type move only once.'),
('Hold items', 'Ghost Memory','Changes Silvally and its move Multi-Attack to Ghost type.'),
('Hold items', 'Ghostium Z','Allows the use of Never-Ending Nightmare, the Ghost type Z-Move.'),
('Hold items', 'Glalitite','Enables Glalie to Mega Evolve during battle.'),
('Hold items', 'Grass Gem','Increases the power of a Grass-type move only once.'),
('Hold items', 'Grass Memory','Changes Silvally and its move Multi-Attack to Grass type.'),
('Hold items', 'Grassium Z','Allows the use of Bloom Doom, the Grass type Z-Move.'),
('Hold items', 'Grassy Seed','An item to be held by a Pokémon. It boosts Defense on Grassy Terrain. It can only be used once.'),
('Hold items', 'Grip Claw','A Pokémon held item that extends the duration of multiturn attacks like Bind and Wrap.'),
('Hold items', 'Griseous Orb','Increases the power of Dragon- and Ghost-type moves when held by Giratina, and changes it to Origin Forme.'),
('Hold items', 'Ground Gem','Increases the power of a Ground-type move only once.'),
('Hold items', 'Ground Memory','Changes Silvally and its move Multi-Attack to Ground type.'),
('Hold items', 'Groundium Z','Allows the use of Tectonic Rage, the Ground type Z-Move.'),
('Hold items', 'Grubby Hanky','A handkerchief dropped by a regular at Café Warehouse. It smells faintly like a Pokémon.'),
('Hold items', 'Gyaradosite','Enables Gyarados to Mega Evolve during battle.'),
('Hold items', 'Hard Stone','Increases the power of Rock-type moves.'),
('Hold items', 'Heat Rock','A Pokémon held item that extends the duration of the move Sunny Day used by the holder.'),
('Hold items', 'Heavy-Duty Boots','Protects the holder from traps set on the battlefield.'),
('Hold items', 'Heracronite','Enables Heracross to Mega Evolve during battle.'),
('Hold items', 'Hi-tech Earbuds','Strange earbuds that allow you to freely control the volume of various sounds.'),
('Hold items', 'Honor Of Kalos','A precious symbol that is awarded only to an individual who has done great things for the Kalos region.'),
('Hold items', 'Houndoominite','Enables Houndoom to Mega Evolve during battle.'),
('Hold items', 'Ice Gem','Increases the power of an Ice-type move only once.'),
('Hold items', 'Ice Memory','Changes Silvally and its move Multi-Attack to Ice type.'),
('Hold items', 'Icicle Plate','Increases power of Ice-type moves. Changes Arceus'' type to Ice.'),
('Hold items', 'Icium Z','Allows the use of Subzero Slammer, the Ice type Z-Move.'),
('Hold items', 'Icy Rock','A Pokémon held item that extends the duration of the move Hail used by the holder.'),
('Hold items', 'Incinium Z','Allows Incineroar to upgrade Darkest Lariat to a Z-Move, Malicious Moonsault.'),
('Hold items', 'Insect Plate','Increases power of Bug-type moves. Changes Arceus'' type to Bug.'),
('Hold items', 'Intriguing Stone','A rather curious stone that might appear to be valuable to some. It''s all in the eye of the beholder.'),
('Hold items', 'Iron Ball','A Pokémon held item that cuts Speed. It makes Flying-type and levitating holders susceptible to Ground moves.'),
('Hold items', 'Iron Plate','Increases power of Steel-type moves. Changes Arceus'' type to Steel.'),
('Hold items', 'Kangaskhanite','Enables Kangaskhan to Mega Evolve during battle.'),
('Hold items', 'King''s Rock','May cause opponent to flinch. Evolves Poliwhirl and Slowpoke when traded holding the item.'),
('Hold items', 'Kommonium Z','Allows Kommo-o to upgrade Clanging Scales to a Z-Move, Clangorous Soulblaze.'),
('Hold items', 'Lagging Tail','Holder always attacks last.'),
('Hold items', 'Latiasite','Enables Latias to Mega Evolve during battle.'),
('Hold items', 'Latiosite','Enables Latios to Mega Evolve during battle.'),
('Hold items', 'Lax Incense','Lowers the opponent''s accuracy. Breeding Wobbuffet produces Wynaut when held.'),
('Hold items', 'Leek','Increases critical-hit ratio when held by Farfetch''d.'),
('Hold items', 'Leftovers','An item to be held by a Pokémon. The holder''s HP is gradually restored during battle.'),
('Hold items', 'Life Orb','Increases the power of moves, but loses HP each turn.'),
('Hold items', 'Light Ball','An item to be held by PIKACHU. It is a puzzling orb that raises the Attack and Sp. Atk stat.'),
('Hold items', 'Light Clay','A Pokémon held item that extends the duration of barrier moves like Light Screen and Reflect used by the holder.'),
('Hold items', 'Looker Ticket','A ticket that was handmade by Looker. It''s decorated with a liberal amount of glittery paint.'),
('Hold items', 'Lopunnite','Enables Lopunny to Mega Evolve during battle.'),
('Hold items', 'Love Sweet','Evolves Milcery into Heart Flavor Alcremie.'),
('Hold items', 'Lucarionite','Enables Lucario to Mega Evolve during battle.'),
('Hold items', 'Luck Incense','Doubles prize money if held. Breeding Chansey or Blissey produces Happiny when held.'),
('Hold items', 'Lucky Egg','An item to be held by a Pokémon. It is an egg filled with happiness that earns extra Exp. Points in battle.'),
('Hold items', 'Lucky Punch','Increases critical-hit ratio when held by Chansey.'),
('Hold items', 'Luminous Moss','Raises Special Defense if hit by a Water-type move.'),
('Hold items', 'Lunalium Z','Allows Lunala to upgrade Moongeist Beam to a Z-Move, Menacing Moonraze Maelstrom.'),
('Hold items', 'Lustrous Orb','Increases the power of Dragon- and Water-type moves when held by Palkia.'),
('Hold items', 'Lycanium Z','Allows Lycanroc to upgrade Stone Edge to a Z-Move, Splintered Stormshards.'),
('Hold items', 'Macho Brace','An item to be held by a Pokémon. It is a stiff and heavy brace that promotes strong growth but lowers Speed.'),
('Hold items', 'Magnet','Increases the power of Electric-type moves.'),
('Hold items', 'Manectite','Enables Manectric to Mega Evolve during battle.'),
('Hold items', 'Marshadium Z','Allows Marshadow to upgrade Spectral Thief to a Z-Move, Soul-Stealing 7-Star Strike.'),
('Hold items', 'Mawilite','Enables Mawile to Mega Evolve during battle.'),
('Hold items', 'Meadow Plate','Increases power of Grass-type moves. Changes Arceus'' type to Grass.'),
('Hold items', 'Medichamite','Enables Medicham to Mega Evolve during battle.'),
('Hold items', 'Mental Herb','An item to be held by a Pokémon. It snaps the holder out of infatuation. It can be used only once.'),
('Hold items', 'Metagrossite','Enables Metagross to Mega Evolve during battle.'),
('Hold items', 'Metal Coat','Increases the power of Steel-type moves. Evolves Onix and Scyther when traded holding the item.'),
('Hold items', 'Metal Powder','Increases Defense when held by Ditto.'),
('Hold items', 'Metronome','Increases the power of moves used consecutively.'),
('Hold items', 'Mewnium Z','Allows Mew to upgrade Psychic to a Z-Move, Genesis Supernova.'),
('Hold items', 'Mewtwonite X','Enables Mewtwo to Mega Evolve during battle.'),
('Hold items', 'Mewtwonite Y','Enables Mewtwo to Mega Evolve during battle.'),
('Hold items', 'Mimikium Z','Allows Mimikyu to upgrade Play Rough to a Z-Move, Let''s Snuggle Forever.'),
('Hold items', 'Mind Plate','Increases power of Psychic-type moves. Changes Arceus'' type to Psychic.'),
('Hold items', 'Miracle Seed','Increases the power of Grass-type moves.'),
('Hold items', 'Misty Seed','An item to be held by a Pokémon. It boosts Sp. Def on Misty Terrain. It can only be used once.'),
('Hold items', 'Muscle Band','Increases the power of Physical-category moves.'),
('Hold items', 'Mystic Water','Increases the power of Water-type moves.'),
('Hold items', 'Never-Melt Ice','Increases the power of Ice-type moves.'),
('Hold items', 'Normal Gem','Increases the power of a Normal-type move only once.'),
('Hold items', 'Normalium Z','Allows the use of Breakneck Blitz, the Normal type Z-Move.'),
('Hold items', 'Odd Incense','Increases the power of Psychic-type moves. Breeding Mr. Mime produces Mime Jr. when held.'),
('Hold items', 'Pass Orb','A mysterious orb containing the power of the Unova region, to be used when generating Pass Power.'),
('Hold items', 'Pidgeotite','Enables Pidgeot to Mega Evolve during battle.'),
('Hold items', 'Pikanium Z','Allows Pikachu to upgrade Volt Tackle to a Z-Move, Catastropika.'),
('Hold items', 'Pikashunium Z','Allows Pikachu in a cap to upgrade Thunderbolt to a Z-Move, 10,000,000 Volt Thunderbolt.'),
('Hold items', 'Pink Nectar','The flower nectar obtained at the flowering shrubs on Royal Avenue. It changes the form of certain species of Pokémon.'),
('Hold items', 'Pinsirite','Enables Pinsir to Mega Evolve during battle.'),
('Hold items', 'Pixie Plate','Increases power of Fairy-type moves. Changes Arceus'' type to Fairy.'),
('Hold items', 'Plasma Card','A card key needed to enter the password inside the Plasma Frigate.'),
('Hold items', 'Poison Barb','Increases the power of Poison-type moves.'),
('Hold items', 'Poison Gem','Increases the power of a Poison-type move only once.'),
('Hold items', 'Poison Memory','Changes Silvally and its move Multi-Attack to Poison type.'),
('Hold items', 'Poisonium Z','Allows the use of Acid Downpour, the Poison type Z-Move.'),
('Hold items', 'Power Anklet','A Pokémon held item that promotes Speed gain on leveling, but reduces the Speed stat.'),
('Hold items', 'Power Band','A Pokémon held item that promotes Sp. Def gain on leveling, but reduces the Speed stat.'),
('Hold items', 'Power Belt','A Pokémon held item that promotes Defense gain on leveling, but reduces the Speed stat.'),
('Hold items', 'Power Bracer','A Pokémon held item that promotes Attack gain on leveling, but reduces the Speed stat.'),
('Hold items', 'Power Herb','A single-use item to be held by a Pokémon. It allows the immediate use of a move that charges on the first turn.'),
('Hold items', 'Power Lens','A Pokémon held item that promotes Sp. Atk gain on leveling, but reduces the Speed stat.'),
('Hold items', 'Power Plant Pass','This pass serves as an ID card for gaining access to the power plant that lies along Route 13.'),
('Hold items', 'Power Weight','A Pokémon held item that promotes HP gain on leveling, but reduces the Speed stat.'),
('Hold items', 'Primarium Z','Allows Primarina to upgrade Sparkling Aria to a Z-Move, Oceanic Operetta.'),
('Hold items', 'Prison Bottle','Transforms Hoopa Confined to Hoopa Unbound.'),
('Hold items', 'Prof''s Letter','A letter that Professor Sycamore wrote to your mother. A faint but pleasant perfume seems to cling to the paper.'),
('Hold items', 'Protective Pads','An item to be held by a Pokémon. These pads protect the holder from effects caused by making direct contact with the target.'),
('Hold items', 'Psychic Gem','Increases the power of a Psychic-type move only once.'),
('Hold items', 'Psychic Memory','Changes Silvally and its move Multi-Attack to Psychic type.'),
('Hold items', 'Psychic Seed','An item to be held by a Pokémon. It boosts Sp. Def on Psychic Terrain. It can only be used once.'),
('Hold items', 'Psychium Z','Allows the use of Shattered Psyche, the Psychic type Z-Move.'),
('Hold items', 'Pure Incense','Descreases the likelihood of meeting wild Pokémon. Breeding Chimecho produces Chingling when held.'),
('Hold items', 'Purple Nectar','A flower nectar obtained at Poni Meadow. It changes the form of certain species of Pokémon.'),
('Hold items', 'Quick Claw','An item to be held by a Pokémon. A light, sharp claw that lets the bearer move first occasionally.'),
('Hold items', 'Quick Powder','Increases Speed when held by Ditto.'),
('Hold items', 'Razor Claw','Increases critical-hit ratio. Evolves Sneasel when held at night.'),
('Hold items', 'Razor Fang','May cause opponent to flinch. Evolves Gligar when held at night.'),
('Hold items', 'Red Card','A card with a mysterious power. When the holder is struck by a foe, the attacker is removed from battle.'),
('Hold items', 'Red Nectar','A flower nectar obtained at Ula''ula Meadow. It changes the form of certain species of Pokémon.'),
('Hold items', 'Ribbon Sweet','Evolves Milcery into Ribbon Flavor Alcremie.'),
('Hold items', 'Ring Target','Moves that would otherwise have no effect will land on the Pokémon that holds it.'),
('Hold items', 'Rock Gem','Increases the power of a Rock-type move only once.'),
('Hold items', 'Rock Incense','Increases the power of Rock-type moves. Breeding Sudowoodo produces Bonsly when held.'),
('Hold items', 'Rock Memory','Changes Silvally and its move Multi-Attack to Rock type.'),
('Hold items', 'Rockium Z','Allows the use of Continental Crush, the Rock type Z-Move.'),
('Hold items', 'Rocky Helmet','If the holder of this item takes damage, the attacker will also be damaged upon contact.'),
('Hold items', 'Room Service','Lowers the Pokémon''s speed during Trick Room.'),
('Hold items', 'Rose Incense','Increases the power of Grass-type moves. Breeding Roselia or Roserade produces Budew when held.'),
('Hold items', 'Sablenite','Enables Sableye to Mega Evolve during battle.'),
('Hold items', 'Safety Goggles','Prevents damage from weather and powder.'),
('Hold items', 'Salamencite','Enables Salamence to Mega Evolve during battle.'),
('Hold items', 'Sceptilite','Enables Sceptile to Mega Evolve during battle.'),
('Hold items', 'Scizorite','Enables Scizor to Mega Evolve during battle.'),
('Hold items', 'Scope Lens','Increases critical-hit ratio.'),
('Hold items', 'Sea Incense','Increases the power of Water-type moves. Breeding Marill or Azumarill produces Azurill when held.'),
('Hold items', 'Sharp Beak','Increases the power of Flying-type moves.'),
('Hold items', 'Sharpedonite','Enables Sharpedo to Mega Evolve during battle.'),
('Hold items', 'Shed Shell','A tough, discarded carapace to be held by a Pokémon. It enables the holder to switch with a waiting Pokémon in battle.'),
('Hold items', 'Shell Bell','An item to be held by a Pokémon. The holder''s HP is restored a little every time it inflicts damage.'),
('Hold items', 'Shock Drive','Changes Techno Blast to an Electric-type move when held by Genesect.'),
('Hold items', 'Silk Scarf','Increases the power of Normal-type moves.'),
('Hold items', 'Silver Powder','Increases the power of Bug-type moves.'),
('Hold items', 'Sky Plate','Increases power of Flying-type moves. Changes Arceus'' type to Flying.'),
('Hold items', 'Slowbronite','Enables Slowbro to Mega Evolve during battle.'),
('Hold items', 'Smoke Ball','An item to be held by a Pokémon. It enables the holder to flee from any wild Pokémon without fail.'),
('Hold items', 'Smooth Rock','A Pokémon held item that extends the duration of the move Sandstorm used by the holder.'),
('Hold items', 'Snorlium Z','Allows Snorlax to upgrade Giga Impact to a Z-Move, Pulverizing Pancake.'),
('Hold items', 'Snowball','Raises Attack if hit by an Ice-type move.'),
('Hold items', 'Soft Sand','Increases the power of Ground-type moves.'),
('Hold items', 'Solganium Z','Allows Solgaleo to upgrade Sunsteel Strike to a Z-Move, Searing Sunraze Smash.'),
('Hold items', 'Soothe Bell','An item to be held by a Pokémon. It is a bell with a comforting chime that calms the holder and makes it friendly.'),
('Hold items', 'Soul Dew','Increases the power of Psychic- and Dragon-type moves when held by Latios or Latias. Increases Sp.Atk/Sp.Def prior to Gen 7.'),
('Hold items', 'Spell Tag','Increases the power of Ghost-type moves.'),
('Hold items', 'Splash Plate','Increases power of Water-type moves. Changes Arceus'' type to Water.'),
('Hold items', 'Spooky Plate','Increases power of Ghost-type moves. Changes Arceus'' type to Ghost.'),
('Hold items', 'Star Sweet','Evolves Milcery into Star Flavor Alcremie.'),
('Hold items', 'Steel Gem','Increases the power of a Steel-type move only once.'),
('Hold items', 'Steel Memory','Changes Silvally and its move Multi-Attack to Steel type.'),
('Hold items', 'Steelium Z','Allows the use of Corkscrew Crash, the Steel type Z-Move.'),
('Hold items', 'Steelixite','Enables Steelix to Mega Evolve during battle.'),
('Hold items', 'Sticky Barb','A held item that damages the holder on every turn. It may latch on to foes and allies that touch the holder.'),
('Hold items', 'Stone Plate','Increases power of Rock-type moves. Changes Arceus'' type to Rock.'),
('Hold items', 'Strawberry Sweet','Evolves Milcery into Strawberry Flavor Alcremie.'),
('Hold items', 'Swampertite','Enables Swampert to Mega Evolve during battle.'),
('Hold items', 'Sweet Apple','Evolves Applin into Appletun.'),
('Hold items', 'Tapunium Z','Allows the Tapus to upgrade Nature''s Madness to a Z-Move, Guardian of Alola.'),
('Hold items', 'Tart Apple','Evolves Applin into Flapple.'),
('Hold items', 'Terrain Extender','An item to be held by a Pokémon. It extends the duration of the terrain caused by the holder''s move or Ability.'),
('Hold items', 'Thick Club','Increases Attack when held by Cubone or Marowak.'),
('Hold items', 'Throat Spray','Raises Sp. Atk when a sound-based move is used.'),
('Hold items', 'Toxic Orb','An item to be held by a Pokémon. It is a bizarre orb that badly poisons the holder in battle.'),
('Hold items', 'Toxic Plate','Increases power of Poison-type moves. Changes Arceus'' type to Poison.'),
('Hold items', 'Twisted Spoon','Increases the power of Psychic-type moves.'),
('Hold items', 'Tyranitarite','Enables Tyranitar to Mega Evolve during battle.'),
('Hold items', 'Ultranecrozium Z','Allows Ultra Necrozma to upgrade Photon Geyser to a Z-Move, Light That Burns the Sky.'),
('Hold items', 'Utility Umbrella','An item to be held by a Pokémon. This sturdy umbrella protects the holder from the effects of weather.'),
('Hold items', 'Venusaurite','Enables Venusaur to Mega Evolve during battle.'),
('Hold items', 'Water Gem','Increases the power of a Water-type move only once.'),
('Hold items', 'Water Memory','Changes Silvally and its move Multi-Attack to Water type.'),
('Hold items', 'Waterium Z','Allows the use of Hydro Vortex, the Water type Z-Move.'),
('Hold items', 'Wave Incense','Increases the power of Water-type moves. Breeding Mantine produces Mantyke when held.'),
('Hold items', 'Weakness Policy','Sharply raises Attack and Special Attack if hit by a super-effective move.'),
('Hold items', 'White Herb','An item to be held by a POKéMON. It restores any lowered stat in battle. It can be used only once.'),
('Hold items', 'Wide Lens','Increases the accuracy of moves.'),
('Hold items', 'Wise Glasses','Increases the power of Special-category moves.'),
('Hold items', 'Yellow Nectar','A flower nectar obtained at Melemele Meadow. It changes the form of certain species of Pokémon.'),
('Hold items', 'Zap Plate','Increases power of Electric-type moves. Changes Arceus'' type to Electric.'),
('Hold items', 'Zoom Lens','Raises a move''s accuracy if the holder moves after its target.');

SELECT * FROM HeldItem;


*/