USE PokemonVGC;

--DROP TABLE IF EXISTS TeamBattle;
DROP TABLE IF EXISTS TeamVGC;

CREATE TABLE TeamVGC
(
teamVGCID INT NOT NULL IDENTITY
	CONSTRAINT PK_TeamVGC PRIMARY KEY,
userID INT NOT NULL,
teamBaseID INT NOT NULL,
pkmnVGCOneID INT NOT NULL,
pkmnVGCTwoID INT NOT NULL,
pkmnVGCThreeID INT NOT NULL,
pkmnVGCFourID INT NOT NULL
);

ALTER TABLE TeamVGC
	ADD CONSTRAINT FK_User_ID_VGC
	FOREIGN KEY (userID)
	REFERENCES VGCPlayer(userID);

ALTER TABLE TeamVGC
	ADD CONSTRAINT FK_BaseTeam_VGCTeam
	FOREIGN KEY (teamBaseID)
	REFERENCES TeamBase(teamBaseID);

ALTER TABLE TeamVGC
	ADD CONSTRAINT FK_Pokemon_ID_One_VGC
	FOREIGN KEY (pkmnVGCOneID)
	REFERENCES Pokemon(pokemonID);

ALTER TABLE TeamVGC
	ADD CONSTRAINT FK_Pokemon_ID_Two_VGC
	FOREIGN KEY (pkmnVGCTwoID)
	REFERENCES Pokemon(pokemonID);

ALTER TABLE TeamVGC
	ADD CONSTRAINT FK_Pokemon_ID_Three_VGC
	FOREIGN KEY (pkmnVGCThreeID)
	REFERENCES Pokemon(pokemonID);

ALTER TABLE TeamVGC
	ADD CONSTRAINT FK_Pokemon_ID_Four_VGC
	FOREIGN KEY (pkmnVGCFourID)
	REFERENCES Pokemon(pokemonID);

SELECT * FROM TeamVGC;